serverPort           : 8080
dbHost               : postgres
dbPort               : 5432
dbUser               : ergvein
dbPassword           : ergvein
dbName               : ergvein
BTCNodeIsTestnet     : true
BTCNodeHost          : 172.17.0.1
BTCNodePort          : 18332
BTCNodeUser          : bitcoinrpcuser
BTCNodePassword      : bitcoinrpcpassword
ERGONodeHost         : 172.17.0.1
ERGONodePort         : 9052
blockchainScanDelay  : 1000000
dbLog                : true
pubScriptHistoryScan : false
cachePath            : "/cache"
