version: "2.4"
volumes:
  ergveindata:
    name: ergveindata
services:
  ergvein-index-server:
    image: ergvein/ergvein-index-server
    container_name: ergvein-index-server
    command: ["listen", "/config/config.yml"]
    ports:
    - 8667:8667
    volumes:
    - ./config:/config
    - ergveindata:/ergveindata
    restart: always
    logging:
      options:
        max-size: "100m"
        max-file: "10"
