version: '2.4'
volumes:
  ergodata:
    name: ergodata
services:
  ergo:
    image: ergoplatform/ergo
    container_name: ergo
    restart: "always"
    entrypoint: ["java", "-jar", "-Dlogback.stdout.level=INFO", "/home/ergo/ergo.jar"]
    command: ["--${CHAIN:-main}net"]
    volumes:
    - ergodata:/home/ergo/.ergo
    logging:
      options:
        max-size: "100m"
        max-file: "10"
