version: "2.4"
volumes:
  pgdata:
    name: pgdata
  cache:
    name: ergvein-cache
services:
  ergvein-index-server:
    image: ergvein/ergvein-index-server
    container_name: ergvein-index-server
    command: ["listen", "/config.yml"]
    ports:
    - 8080:8080
    volumes:
    - ./config.yml:/config.yml
    - cache:/cache
    restart: always
    depends_on:
    - "postgres"
    logging: &log
      options:
        max-size: "10m"
        max-file: "10"
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
    - POSTGRES_DB=ergvein
    - POSTGRES_USER=ergvein
    - POSTGRES_PASSWORD=ergvein
    volumes:
    - pgdata:/var/lib/postgresql/data
    restart: always
    logging:
      <<: *log

