serverPort               : 8085
serverTcpPort            : 8667
filtersDbPath            : "./ergveinDb_testnet"
indexerDbPath            : "./indexerDb_testnet"
BTCNodeIsTestnet         : true
BTCNodeHost              : localhost
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpc
BTCNodePassword          : password
BTCNodeTCPHost           : localhost
BTCNodeTCPPort           : 18333
ERGONodeHost             : localhost
ERGONodePort             : 9052
blockchainScanDelay      : 10000000
ownPeerAddress           : null
knownPeers               : []
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400
metrics:
  host: localhost
  port: 9667
