serverPort               : 8085
serverTcpPort            : 18667
filtersDbPath            : "./db_testnet_filters"
indexerDbPath            : "./db_testnet_indexer"
utxoDbPath               : "./db_testnet_utxo"
BTCNodeIsTestnet         : true
BTCNodeHost              : localhost
BTCNodePort              : 18332
BTCNodeUser              : bitcoinrpc
BTCNodePassword          : password
BTCNodeTCPHost           : localhost
BTCNodeTCPPort           : 18333
blockchainScanDelay      : 10000000
ownPeerAddress           : null
knownPeers               : []
peerActualizationDelay   : 10000000
peerActualizationTimeout : 86400
ratesRefreshPeriod       : 300000000          # 5 minutes
metrics:
  host: localhost
  port: 9667
